name: acidtime
description: Get the current time in an eccentric way.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
flutter:
  uses-material-design: true
  fonts:
    - family: LSD
      fonts:
        - asset: assets/fonts/LSD.ttf
